server {
    listen 80;
    server_name examen.local;

    # Redirección HTTP a HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name www.frandaw.com;

    # Certificados SSL (Certbot / Let's Encrypt)
    # CAMBIA 'TU_DOMINIO.COM' POR TU DOMINIO REAL (ej. miweb.com)
    ssl_certificate /etc/letsencrypt/live/www.frandaw.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.frandaw.com/privkey.pem;

    # Certificados SSL (Autofirmados - Comentar si usas Certbot)
    # ssl_certificate /etc/nginx/certs/server.crt;
    # ssl_certificate_key /etc/nginx/certs/server.key;

    # Rutas para el Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy Inverso para el Backend PHP
    location /api/ {
        # Reescribimos la URL para quitar /api/ antes de enviarla al backend si es necesario
        # En este caso, si el backend espera recibir requests en la raiz, usamos rewrite.
        # Pero como el enunciado dice "index.php", asumimos que está en la raiz del docker de php.
        rewrite ^/api/(.*) /$1 break;
        
        proxy_pass http://app:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
